name: Veracode Static Analysis Demo
on: workflow_dispatch
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven # Compiling the .war binary from the checked out repo source code to upload to the scanner in the next step
        run: mvn -B package --file app/pom.xml
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.11
        with:
          appname: 'RRRTEST1'
          createprofile: false
          filepath: 'app/target/verademo.war'
          vid: '8182c46d6381e81caf3b09e573145e1e'
          vkey: '05b26fd4739f206a4f19b5772bfe3b50c029d9dc22ca1ffe56d18458d7e3a8be89c693f84b1d5c9b05dbfaf7dbecb6a5840e343686dbc137d21d80364a91656c'
          createsandbox: 'true'
          sandboxname: 'March11'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
